version: '3.8' 

services:
  app:
    container_name: "discover-be"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    deploy: 
      resources: 
        limits:
          cpus: '0.25'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 100M
